const sty={n:['#ffffff','#e2e8f0','#0f172a'],i:['#e0e7ff','#a5b4fc','#312e81'],g:['#dcfce7','#86efac','#14532d'],s:['#f8fafc','#94a3b8','#334155']};
function esc(s){return s.replace(/&(?!amp;)/g,'&amp;');}
function diagram(id,W,H,boxes,edges,notes){
  notes=notes||[];const M={};boxes.forEach(b=>M[b.id]=b);
  const cy=b=>b.y+b.h/2;
  const paths=edges.map(e=>{const a=M[e[0]],b=M[e[1]];const sx=a.x+a.w,sy=cy(a),ex=b.x-3,ey=cy(b);const bx=e[2]!=null?e[2]:Math.round((sx+ex)/2);
    if(Math.abs(sy-ey)<1)return `M${sx},${sy} L${ex},${ey}`;const r=Math.min(10,Math.abs(ey-sy)/2,Math.abs(bx-sx),Math.abs(ex-bx));const dy=Math.sign(ey-sy);
    return `M${sx},${sy} L${bx-r},${sy} Q${bx},${sy} ${bx},${sy+dy*r} L${bx},${ey-dy*r} Q${bx},${ey} ${bx+r},${ey} L${ex},${ey}`;});
  const svg=`<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="position:absolute;inset:0;overflow:visible" aria-hidden="true"><defs><marker id="${id}-a" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M1,1 L8,5 L1,9" fill="none" stroke="#94a3b8" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"></path></marker></defs>${paths.map(d=>`<path d="${d}" fill="none" stroke="#94a3b8" stroke-width="1.6" stroke-linecap="round" marker-end="url(#${id}-a)"></path>`).join('')}</svg>`;
  const bx=boxes.map(b=>{const c=sty[b.k||'n'];const list=b.items?`<ul style="display:flex;flex-direction:column;gap:2px;margin:0;padding-left:14px;text-align:left">${b.items.map(t=>`<li style="font-size:10.5px;line-height:1.35;color:#475569">${esc(t)}</li>`).join('')}</ul>`:'';
    return `<div style="position:absolute;left:${b.x}px;top:${b.y}px;width:${b.w}px;height:${b.h}px;display:flex;flex-direction:column;justify-content:center;align-items:${b.items?'flex-start':'center'};gap:5px;padding:8px 10px;text-align:${b.items?'left':'center'};background:${c[0]};border:1px ${b.k==='s'?'dashed':'solid'} ${c[1]};border-radius:10px;box-shadow:0 1px 2px rgba(15,23,42,.04),0 6px 14px -10px rgba(15,23,42,.25)"><span style="font-size:11.5px;font-weight:700;line-height:1.3;color:${c[2]};text-wrap:balance">${esc(b.t)}</span>${list}</div>`;}).join('\n');
  const nt=notes.map(n=>`<div style="position:absolute;left:${n.x}px;top:${n.y}px;width:${n.w}px;padding:20px 14px 14px;background:${n.bg};border:1px solid ${n.bd};border-radius:3px;box-shadow:0 12px 20px -12px rgba(15,23,42,.35);transform:rotate(${n.r})"><span style="position:absolute;top:-7px;left:50%;width:14px;height:14px;margin-left:-7px;border-radius:99px;background:radial-gradient(circle at 35% 30%,#ffffff 0,${n.pin} 45%,${n.pin} 100%);box-shadow:0 2px 3px rgba(15,23,42,.3)"></span><span style="display:block;font-size:10px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#64748b;margin-bottom:6px">${n.label}</span><span style="display:block;font-size:11.5px;line-height:1.45;color:#1f2937">${esc(n.t)}</span></div>`).join('');
  return `<div style="overflow-x:auto;border:1px solid #e5e7eb;border-radius:20px;background-color:#fafbff;background-image:radial-gradient(#e2e8f0 1px,transparent 1px);background-size:18px 18px"><div style="width:${W}px;margin:28px auto;padding:0 24px;box-sizing:content-box"><div style="position:relative;width:${W}px;height:${H}px">${svg}${bx}${nt}</div></div></div>`;
}
function li(a){return `<ul style="display:flex;flex-direction:column;gap:5px;margin:0;padding-left:16px">${a.map(x=>typeof x==='string'?`<li>${esc(x)}</li>`:`<li><strong style="color:#0f172a">${esc(x[0])}</strong>${li(x[1]).replace('margin:0','margin:4px 0 0')}</li>`).join('')}</ul>`;}
function table(cols,rows,minW){const td='padding:14px 16px;border-top:1px solid #e5e7eb;border-left:1px solid #e5e7eb;vertical-align:top;font-size:13px;line-height:1.55;color:#374151';
  return `<div style="overflow-x:auto;border:1px solid #e5e7eb;border-radius:16px;background:#ffffff"><table style="width:100%;min-width:${minW}px;border-collapse:collapse;text-align:left"><thead><tr><th style="padding:14px 16px;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#6b7280;background:#f8fafc;vertical-align:top">Steps</th>${cols.map(c=>`<th style="padding:14px 16px;border-left:1px solid #e5e7eb;font-size:14px;font-weight:800;color:#0f172a;background:#f8fafc;vertical-align:top">${esc(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><th scope="row" style="${td};border-left:none;font-weight:700;color:#0f172a;white-space:nowrap">${esc(r[0])}</th>${r[1].map(c=>`<td style="${td}">${Array.isArray(c)?li(c):esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const legend=`<div style="display:flex;gap:18px;flex-wrap:wrap">${[['#e0e7ff','#a5b4fc','Entry point','solid'],['#ffffff','#cbd5e1','User step','solid'],['#f8fafc','#94a3b8','System step','dashed'],['#dcfce7','#86efac','Outcome','solid']].map(v=>`<span style="display:inline-flex;align-items:center;gap:8px;font-size:13px;color:#475569"><span style="width:14px;height:14px;border-radius:4px;background:${v[0]};border:1px ${v[3]} ${v[1]}"></span>${v[2]}</span>`).join('')}</div>`;
function wrap(d,t){return `<div style="display:flex;flex-direction:column;gap:16px">${legend}${d}${t}</div>`;}
return {diagram,table,wrap};
